# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: feixian8
subtitle: 菲闲8
description: 专注分享菲律宾华人生活圈的有关信息，并记录一些不法商人或个人的不良记录
keywords: 菲律宾华人,菲律宾华人生活信息,菲律宾华人奸商曝光
author: feixian8
language:
timezone:
#压缩
neat_enable: true
neat_html:
  enable: true
  exclude:
    - '*/themes/**/*/*.ejs'
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.feixian8.com
root: /
permalink: :year/:month/:day/:title/
#permalink_defaults:
#  lang: en
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
 
disqus_shortname: feixian8

widgets:
#  - widget: list
#    icon: fas fa-medal
#    title: 精选项目
#    more:
#      icon: fas fa-arrow-right
#      url: https://xaoxuu.com/projects/
#    rows:
#      - name: AXKit
#        desc: iOS开源库
#        icon: fas fa-cube
#        url: https://xaoxuu.com/wiki/axkit/
#      - name: NoticeBoard
#        desc: iOS开源库
#        icon: fas fa-cube
#        url: https://xaoxuu.com/wiki/noticeboard/
#      - name: HeartMate
#        desc: iOS应用程序
#        icon: fas fa-heartbeat
#        url: https://xaoxuu.com/heartmate/
#      - name: Material X
#        desc: Hexo博客主题
#        icon: fas fa-cube
#        url: https://xaoxuu.com/wiki/material-x/
  - widget: plain
    icon: fas fa-bullhorn
    title: 公告
    body: 'FeiXian8(菲闲吧)，网址[https://www.feixian8.com/](https://www.feixian8.com/) 专注分享菲律宾华人生活圈的有关信息，并记录一些道德败坏份的信息'
  - widget: plain
    icon: fas fa-bullhorn
    title: 建议
    body: '为了获得访问 FeiXian8(菲闲吧) 的最佳体验，我们推荐使用 [Google Chrome](https://www.google.com/chrome/) 或 [Mozilla Firefox](http://www.getfirefox.com/) 浏览器。'
#    more:
#     icon: fas fa-question-circle
#     url: https://xaoxuu.com/wiki/material-x/
#  - widget: plain
#     icon: "fas fa-bullhorn"
#     title: 注意啦～
#     body: ''

footer: '这是页脚文字，支持**markdown**语法。'
menu:
  - name: 首页
    icon: fas fa-home
    url: https://www.feixian8.com/
  - name: 闲置
    icon: fas fa-database
    url: /categories/used/
  - name: 网友分享
    icon: fas fa-coffee
    url: /categories/sharing/
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


